package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setUserId(Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public Integer getUserId() {
		return get("user_id");
	}

	public M setStudentId(Long studentId) {
		set("student_id", studentId);
		return (M)this;
	}

	public Long getStudentId() {
		return get("student_id");
	}

	public M setUserName(String userName) {
		set("user_name", userName);
		return (M)this;
	}

	public String getUserName() {
		return get("user_name");
	}

	public M setUserGender(String userGender) {
		set("user_gender", userGender);
		return (M)this;
	}

	public String getUserGender() {
		return get("user_gender");
	}

	public M setUserEmail(String userEmail) {
		set("user_email", userEmail);
		return (M)this;
	}

	public String getUserEmail() {
		return get("user_email");
	}

	public M setUserQq(Long userQq) {
		set("user_qq", userQq);
		return (M)this;
	}

	public Long getUserQq() {
		return get("user_qq");
	}

	public M setUserTel(Long userTel) {
		set("user_tel", userTel);
		return (M)this;
	}

	public Long getUserTel() {
		return get("user_tel");
	}

	public M setUserDesc(String userDesc) {
		set("user_desc", userDesc);
		return (M)this;
	}

	public String getUserDesc() {
		return get("user_desc");
	}

	public M setApplyTime(String applyTime) {
		set("apply_time", applyTime);
		return (M)this;
	}

	public String getApplyTime() {
		return get("apply_time");
	}

}
